# Generated by Django 4.1.4 on 2023-01-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=40, verbose_name='Тип')),
                ('title', models.CharField(max_length=40, verbose_name='Название')),
                ('task', models.TextField(verbose_name='Описание')),
                ('priority', models.CharField(max_length=40, verbose_name='Приоритет')),
                ('deadline', models.CharField(max_length=40, verbose_name='Сроки выполнения')),
            ],
        ),
    ]
