# Generated by Django 4.1.4 on 2023-01-14 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0002_alter_task_options_remove_task_deadline_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='type',
        ),
        migrations.AddField(
            model_name='task',
            name='task',
            field=models.TextField(default='', verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
